// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW3tx8QZvdpElBl9F_JXtG_uhhXqkHZJM',
    appId: '1:14033899360:web:7a1f66fa639bff8b075805',
    messagingSenderId: '14033899360',
    projectId: 'test-5184a',
    authDomain: 'test-5184a.firebaseapp.com',
    databaseURL: 'https://test-5184a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-5184a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxw9QW3ne4VkwflnoeWbPyuYwZZNXMBo4',
    appId: '1:14033899360:android:245494572f8b91aa075805',
    messagingSenderId: '14033899360',
    projectId: 'test-5184a',
    databaseURL: 'https://test-5184a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-5184a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxrc0brwK0m5lzBjFLjD4z2YRdcZPjuCY',
    appId: '1:14033899360:ios:8fedc2e9ef858ebc075805',
    messagingSenderId: '14033899360',
    projectId: 'test-5184a',
    databaseURL: 'https://test-5184a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-5184a.appspot.com',
    iosBundleId: 'com.example.tabviewFlutterModule',
  );
}
